TRAIN:
  DATASET: fmf_video
  BATCH_SIZE: 64
DATA:
  PATH_TO_DATA_DIR: ''
  NUM_FRAMES: 8
  SAMPLING_RATE: 19
  IMAGE_SIZE: 64
SOLVER:
  BASE_LR: 0.0005
  LR_POLICY: step
  COSINE_END_LR: 0.
  STEPS: [20]
  MAX_EPOCH: 30
MODEL:
  MODEL_NAME: vit_for_video
  NUM_CLASSES: 2
  IMAGE_PATCH_SIZE: 8
  FRAME_PATCH_SIZE: 2
  PETYPE: learnable
  ADDITIONAL_TOKENS: True
  PRETRAINED: ''
TEST:
  DATASET: fmf_video
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
OUTPUT_DIR: ''
PRINT_FREQ: 100
TASK: classification
