TRAIN:
  DATASET: fmf_current
  BATCH_SIZE: 64
DATA:
  PATH_TO_DATA_DIR: './data/FMFBenchmarkV2/pixel-level'
  CURRENT_SECONDS: 120
  CURRENT_PATCH_DIMS: 3
SOLVER:
  BASE_LR: 0.0005
  LR_POLICY: step
  COSINE_END_LR: 0.
  STEPS: [20]
  MAX_EPOCH: 30
MODEL:
  MODEL_NAME: vit_for_current
  NUM_CLASSES: 2
  PRETRAINED: ''
TEST:
  DATASET: fmf_current
  BATCH_SIZE: 64
DATA_LOADER:
  NUM_WORKERS: 2
  PIN_MEMORY: True
OUTPUT_DIR: ''
PRINT_FREQ: 20

